name: Testar NestJS com Docker Compose

on:
  push:
    branches:
      - main

jobs:
  test-server:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Criar `.env.test`
        run: |
          echo "DB_HOST=mysqldb" >> .env.test
          echo "DB_PORT=3306" >> .env.test
          echo "DB_USER=root" >> .env.test
          echo "DB_PASSWORD=senha_root_123" >> .env.test
          echo "DB_NAME=wefit" >> .env.test

      - name: ğŸš€ Subir containers com Docker Compose
        run: docker compose -f ./docker-compose.yml up -d

      - name: â³ Aguardar banco de dados
        run: |
          echo "Aguardando banco de dados..."
          sleep 15  # Tempo suficiente para o MySQL iniciar

      - name: âœ… Rodar testes dentro do container
        run: docker compose exec -T app npm test

      - name: ğŸ›‘ Parar e remover containers
        run: docker-compose down
